### PR TITLE
Dev Updates 2024

### PR DESCRIPTION
**Pull request by Myoldmopar**
Trying to just apply things we've learned over the years and get things going again.  Right now I get two failures locally, both appearing related to numpy updates, as well as some deprecation warnings.  Otherwise it's close.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Here's the type of message coming from numpy:

```
  /home/runner/work/GLHE/GLHE/glhe/profiles/external_base.py:11: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
  You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
  A typical example is when you are setting values in a column of a DataFrame, like:
  
  df["col"][row_indexer] = value
  
  Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.
  
  See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
    df['delta t'].iloc[0] = 0
```

I don't quite see what is going wrong, or what it wants in this case.  I think it's more than likely just me not being well-versed in DataFrames.  @mitchute maybe you could look at it sometime and understand what it is complaining about.

This should be super easy to duplicate:

```sh
pip install -r requirements.txt
coverage run -m pytest
```

**Comment by Myoldmopar** [comment]
I think as a part of this PR, we should: 

- [ ] Bump dependencies up, including GHA setup-python and other actions we are using
- [ ] Update README with new badges
- [ ] Check on ReadTheDocs
- [ ] Fix build/deprecation warnings
- [ ] Consider the structure and codebase one more time
- [ ] Publish on PyPi

After these are all done, we can merge this and then be prepared to refactor it for use in E+.

**Comment by Myoldmopar** [comment]
Here are some things I'd like to do in in the next PR:
- add entry point in setup py 
- isolate (maybe eliminate?) scipy/numpy/pandas
- eliminate matplotlib
- use pathlib

**Comment by Myoldmopar** [comment]
@mitchute this shows merging is blocked until it's approved.  CI looks happy, let me know if you want me to do anything else here :)

**Review by mitchute — APPROVED** [review]
This is great! 💯

**Pull request merged**
